# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0592116883324f275512f867a938833b84e368f96bd1effc7f4ea6dcb4036e3f328c42fd873eafe2a24070c38d82580c3903f84c1b105599383559c9950e61

test:
  secret_key_base: 8c7ccdcd3fd678f7a42bddfac7b09946be5f7c6fad7f219a0e60a9358d1ccc824518266ece0434702ee11b0205bc96678d0634ddbbd7cf2c2de2d98a0a3f0c07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
